-- NOVA unified notification center v1
-- Applied to Supabase project nova-realtime as migration nova_notification_center_v1.
-- Persisted notification history + per-user private Realtime Broadcast.

create table if not exists public.nova_notifications (
  notification_id bigint generated by default as identity primary key,
  recipient_employee_no text not null,
  kind text not null,
  title text not null,
  body text not null default '',
  site text not null default '',
  room_no text not null default '',
  entity_type text not null default '',
  entity_id text not null default '',
  priority text not null default 'NORMAL',
  payload jsonb not null default '{}'::jsonb,
  dedupe_key text unique,
  created_at timestamptz not null default now(),
  read_at timestamptz null
);

create index if not exists nova_notifications_recipient_created_idx
  on public.nova_notifications (recipient_employee_no, created_at desc);
create index if not exists nova_notifications_recipient_unread_idx
  on public.nova_notifications (recipient_employee_no, created_at desc)
  where read_at is null;

alter table public.nova_notifications enable row level security;
revoke all on table public.nova_notifications from public, anon, authenticated;
grant select on table public.nova_notifications to authenticated;
grant update (read_at) on table public.nova_notifications to authenticated;

drop policy if exists "nova notifications read own" on public.nova_notifications;
create policy "nova notifications read own"
on public.nova_notifications for select to authenticated
using (recipient_employee_no = coalesce((select auth.jwt() ->> 'employee_no'), ''));

drop policy if exists "nova notifications mark own read" on public.nova_notifications;
create policy "nova notifications mark own read"
on public.nova_notifications for update to authenticated
using (recipient_employee_no = coalesce((select auth.jwt() ->> 'employee_no'), ''))
with check (recipient_employee_no = coalesce((select auth.jwt() ->> 'employee_no'), ''));

create or replace function nova_private.nova_notification_emit(
  p_employee_no text,
  p_kind text,
  p_title text,
  p_body text default '',
  p_site text default '',
  p_room_no text default '',
  p_entity_type text default '',
  p_entity_id text default '',
  p_priority text default 'NORMAL',
  p_payload jsonb default '{}'::jsonb,
  p_dedupe_key text default null
)
returns bigint
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_employee_no text := btrim(coalesce(p_employee_no, ''));
  v_id bigint;
begin
  if v_employee_no = '' then return null; end if;
  if not exists (
    select 1 from public.nova_users u
    where u.employee_no = v_employee_no and u.enabled = true
  ) then return null; end if;

  insert into public.nova_notifications (
    recipient_employee_no, kind, title, body, site, room_no,
    entity_type, entity_id, priority, payload, dedupe_key
  ) values (
    v_employee_no,
    left(coalesce(p_kind, 'SYSTEM'), 60),
    left(coalesce(p_title, 'NOVA 알림'), 160),
    left(coalesce(p_body, ''), 800),
    left(coalesce(p_site, ''), 80),
    left(coalesce(p_room_no, ''), 40),
    left(coalesce(p_entity_type, ''), 60),
    left(coalesce(p_entity_id, ''), 160),
    left(upper(coalesce(p_priority, 'NORMAL')), 20),
    coalesce(p_payload, '{}'::jsonb),
    nullif(left(coalesce(p_dedupe_key, ''), 240), '')
  )
  on conflict (dedupe_key) do nothing
  returning notification_id into v_id;
  return v_id;
end;
$function$;
revoke all on function nova_private.nova_notification_emit(text,text,text,text,text,text,text,text,text,jsonb,text) from public, anon, authenticated;

create or replace function nova_private.nova_notification_broadcast_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  perform realtime.send(
    to_jsonb(new),
    'NOTIFICATION',
    'nova:user:' || new.recipient_employee_no || ':notifications',
    true
  );
  return new;
end;
$function$;
revoke all on function nova_private.nova_notification_broadcast_trigger() from public, anon, authenticated;

drop trigger if exists nova_notifications_broadcast_trg on public.nova_notifications;
create trigger nova_notifications_broadcast_trg
after insert on public.nova_notifications
for each row execute function nova_private.nova_notification_broadcast_trigger();

create or replace function nova_private.nova_houseman_notification_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_today date := (clock_timestamp() at time zone 'Asia/Seoul')::date;
  v_changed boolean := false;
  v_emp text := btrim(coalesce(new.assigned_employee_no, ''));
  v_priority text := case when coalesce(new.important, false) then 'HIGH' else 'NORMAL' end;
begin
  if new.business_date <> v_today then return new; end if;
  if upper(coalesce(new.status_code, '')) not in ('SAVING','REGISTERED','ASSIGNED','ACCEPTED','PROCESSING') then return new; end if;
  if tg_op = 'INSERT' then
    v_changed := v_emp <> '';
  else
    v_changed := v_emp <> '' and new.assigned_employee_no is distinct from old.assigned_employee_no;
  end if;
  if v_changed then
    perform nova_private.nova_notification_emit(
      v_emp,
      'HOUSEMAN_ASSIGN',
      case when coalesce(new.important, false) then '중요 하우스맨 오더' else '새 하우스맨 오더' end,
      concat_ws(' · ', nullif(new.room_no, '') || '호', nullif(new.item_summary, '')),
      new.site,new.room_no,'HOUSEMAN_ORDER',new.order_id,v_priority,
      jsonb_build_object('route','houseman','site',new.site,'roomNo',new.room_no,'orderId',new.order_id),
      'HOUSEMAN_ASSIGN|' || new.order_id || '|' || v_emp || '|' || coalesce(new.version, 0)::text
    );
  end if;
  return new;
end;
$function$;
revoke all on function nova_private.nova_houseman_notification_trigger() from public, anon, authenticated;
drop trigger if exists nova_houseman_notification_trg on public.nova_houseman_orders;
create trigger nova_houseman_notification_trg
after insert or update of assigned_employee_no, status_code on public.nova_houseman_orders
for each row execute function nova_private.nova_houseman_notification_trigger();

create or replace function nova_private.nova_room_assignment_notification_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_today date := (clock_timestamp() at time zone 'Asia/Seoul')::date;
  v_primary text := btrim(coalesce(new.roommaid_employee_no, ''));
  v_secondary text := btrim(coalesce(new.secondary_roommaid_employee_no, ''));
  v_qm text := btrim(coalesce(new.qm_employee_no, ''));
  v_old_primary text := btrim(coalesce(old.roommaid_employee_no, ''));
  v_old_secondary text := btrim(coalesce(old.secondary_roommaid_employee_no, ''));
begin
  if new.business_date <> v_today then return new; end if;

  if v_primary <> '' and v_primary is distinct from v_old_primary and v_primary is distinct from v_old_secondary then
    perform nova_private.nova_notification_emit(
      v_primary,'ROOMMAID_ASSIGN','새 정비객실 배정',
      concat_ws(' · ', nullif(new.room_no, '') || '호', nullif(new.cleaning_type, '')),
      new.site,new.room_no,'ROOM',new.id::text,'NORMAL',
      jsonb_build_object('route','cleaning','site',new.site,'roomNo',new.room_no),
      'ROOMMAID_ASSIGN|' || new.id::text || '|' || v_primary || '|' || coalesce(new.version, 0)::text
    );
  end if;

  if v_secondary <> '' and v_secondary is distinct from v_primary
     and v_secondary is distinct from v_old_primary and v_secondary is distinct from v_old_secondary then
    perform nova_private.nova_notification_emit(
      v_secondary,'ROOMMAID_ASSIGN','새 정비객실 배정',
      concat_ws(' · ', nullif(new.room_no, '') || '호', nullif(new.cleaning_type, '')),
      new.site,new.room_no,'ROOM',new.id::text,'NORMAL',
      jsonb_build_object('route','cleaning','site',new.site,'roomNo',new.room_no),
      'ROOMMAID_ASSIGN|' || new.id::text || '|' || v_secondary || '|' || coalesce(new.version, 0)::text
    );
  end if;

  if v_qm <> '' and new.qm_employee_no is distinct from old.qm_employee_no then
    perform nova_private.nova_notification_emit(
      v_qm,'QM_ASSIGN','QM 점검객실 배정',concat_ws(' · ', nullif(new.room_no, '') || '호', '점검대상'),
      new.site,new.room_no,'ROOM',new.id::text,'NORMAL',
      jsonb_build_object('route','qm','site',new.site,'roomNo',new.room_no),
      'QM_ASSIGN|' || new.id::text || '|' || v_qm || '|' || coalesce(new.version, 0)::text
    );
  end if;
  return new;
end;
$function$;
revoke all on function nova_private.nova_room_assignment_notification_trigger() from public, anon, authenticated;
drop trigger if exists nova_room_assignment_notification_trg on public.nova_rooms_current;
create trigger nova_room_assignment_notification_trg
after update of roommaid_employee_no, secondary_roommaid_employee_no, qm_employee_no on public.nova_rooms_current
for each row execute function nova_private.nova_room_assignment_notification_trigger();

create or replace function nova_private.nova_room_event_notification_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_today date := (clock_timestamp() at time zone 'Asia/Seoul')::date;
  v_room public.nova_rooms_current%rowtype;
  v_emp text;
  v_key text := coalesce(new.event_id::text, new.id::text);
begin
  if new.business_date <> v_today then return new; end if;
  if upper(coalesce(new.action, '')) not in ('QM_REWORK','CLEANING_COMPLETE') then return new; end if;
  select * into v_room from public.nova_rooms_current r
  where r.business_date = new.business_date and r.site = new.site and r.room_no = new.room_no limit 1;
  if not found then return new; end if;

  if upper(new.action) = 'QM_REWORK' then
    v_emp := btrim(coalesce(v_room.roommaid_employee_no, ''));
    if v_emp <> '' then
      perform nova_private.nova_notification_emit(
        v_emp,'QM_REWORK','QM 재정비 요청',new.room_no || '호 · 재정비가 요청되었습니다.',
        new.site,new.room_no,'ROOM_EVENT',v_key,'HIGH',
        jsonb_build_object('route','cleaning','site',new.site,'roomNo',new.room_no,'eventId',v_key),
        'QM_REWORK|' || v_key || '|' || v_emp
      );
    end if;
    v_emp := btrim(coalesce(v_room.secondary_roommaid_employee_no, ''));
    if v_emp <> '' and v_emp is distinct from btrim(coalesce(v_room.roommaid_employee_no, '')) then
      perform nova_private.nova_notification_emit(
        v_emp,'QM_REWORK','QM 재정비 요청',new.room_no || '호 · 재정비가 요청되었습니다.',
        new.site,new.room_no,'ROOM_EVENT',v_key,'HIGH',
        jsonb_build_object('route','cleaning','site',new.site,'roomNo',new.room_no,'eventId',v_key),
        'QM_REWORK|' || v_key || '|' || v_emp
      );
    end if;
  elsif upper(new.action) = 'CLEANING_COMPLETE' then
    v_emp := btrim(coalesce(v_room.qm_employee_no, ''));
    if v_emp <> '' then
      perform nova_private.nova_notification_emit(
        v_emp,'CLEANING_COMPLETE','청소 완료 · QM 점검 가능',new.room_no || '호 청소가 완료되었습니다.',
        new.site,new.room_no,'ROOM_EVENT',v_key,'NORMAL',
        jsonb_build_object('route','qm','site',new.site,'roomNo',new.room_no,'eventId',v_key),
        'CLEANING_COMPLETE|' || v_key || '|' || v_emp
      );
    end if;
  end if;
  return new;
end;
$function$;
revoke all on function nova_private.nova_room_event_notification_trigger() from public, anon, authenticated;
drop trigger if exists nova_room_event_notification_trg on public.nova_room_events;
create trigger nova_room_event_notification_trg after insert on public.nova_room_events
for each row execute function nova_private.nova_room_event_notification_trigger();

create or replace function nova_private.nova_archive_integrity_notification_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare v_user record;
begin
  if coalesce(new.ok, false) then return new; end if;
  for v_user in select employee_no from public.nova_users where enabled = true and upper(coalesce(role,'')) = 'ADMIN' loop
    perform nova_private.nova_notification_emit(
      v_user.employee_no,'ARCHIVE_ALERT','Archive 무결성 확인 필요',
      'Archive 무결성 점검에서 확인이 필요한 항목이 발생했습니다.',
      '','','ARCHIVE_INTEGRITY',new.snapshot_id::text,'HIGH',
      jsonb_build_object('route','archive','snapshotId',new.snapshot_id),
      'ARCHIVE_INTEGRITY|' || new.snapshot_id::text || '|' || v_user.employee_no
    );
  end loop;
  return new;
end;
$function$;
revoke all on function nova_private.nova_archive_integrity_notification_trigger() from public, anon, authenticated;
drop trigger if exists nova_archive_integrity_notification_trg on public.nova_archive_integrity_snapshots;
create trigger nova_archive_integrity_notification_trg after insert on public.nova_archive_integrity_snapshots
for each row execute function nova_private.nova_archive_integrity_notification_trigger();

create or replace function nova_private.nova_archive_prune_failure_notification_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_user record;
  v_new_failed boolean := upper(coalesce(new.status,'')) = 'FAILED';
  v_old_failed boolean := case when tg_op='UPDATE' then upper(coalesce(old.status,'')) = 'FAILED' else false end;
begin
  if not v_new_failed or v_old_failed then return new; end if;
  for v_user in select employee_no from public.nova_users where enabled = true and upper(coalesce(role,'')) = 'ADMIN' loop
    perform nova_private.nova_notification_emit(
      v_user.employee_no,'ARCHIVE_ALERT','Archive Prune 실패',
      concat_ws(' · ', nullif(new.business_date::text,''), nullif(new.site,''), nullif(new.message,'')),
      new.site,'','ARCHIVE_PRUNE',new.run_id::text,'HIGH',
      jsonb_build_object('route','archive','runId',new.run_id),
      'ARCHIVE_PRUNE_FAILED|' || new.run_id::text || '|' || v_user.employee_no
    );
  end loop;
  return new;
end;
$function$;
revoke all on function nova_private.nova_archive_prune_failure_notification_trigger() from public, anon, authenticated;
drop trigger if exists nova_archive_prune_failure_notification_trg on public.nova_archive_prune_runs;
create trigger nova_archive_prune_failure_notification_trg
after insert or update of status on public.nova_archive_prune_runs
for each row execute function nova_private.nova_archive_prune_failure_notification_trigger();

drop policy if exists "nova notification realtime receive" on realtime.messages;
create policy "nova notification realtime receive"
on realtime.messages for select to authenticated
using (
  extension = 'broadcast'
  and realtime.topic() = ('nova:user:' || coalesce((select auth.jwt() ->> 'employee_no'), '') || ':notifications')
);