-- NOVA PWA + Web Push V2
-- Applied to nova-realtime on 2026-09-06.
-- Secret VALUES are intentionally omitted from source control.
-- Required Vault secret names:
--   nova_web_push_vapid_private_v2
--   nova_web_push_dispatch_token_v2

create table if not exists public.nova_push_subscriptions (
  subscription_id uuid primary key default gen_random_uuid(),
  employee_no text not null,
  endpoint text not null unique,
  p256dh text not null,
  auth_secret text not null,
  user_agent text not null default '',
  platform text not null default '',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_success_at timestamptz null,
  last_failure_at timestamptz null,
  failure_count integer not null default 0,
  last_error text not null default ''
);

create index if not exists nova_push_subscriptions_employee_enabled_idx
  on public.nova_push_subscriptions (employee_no, enabled, updated_at desc);

alter table public.nova_push_subscriptions enable row level security;
revoke all on table public.nova_push_subscriptions from public, anon, authenticated;
grant select, insert, update, delete on table public.nova_push_subscriptions to authenticated;

drop policy if exists "nova push subscriptions read own" on public.nova_push_subscriptions;
create policy "nova push subscriptions read own"
on public.nova_push_subscriptions for select to authenticated
using (employee_no = coalesce(((select auth.jwt()) ->> 'employee_no'), ''));

drop policy if exists "nova push subscriptions insert own" on public.nova_push_subscriptions;
create policy "nova push subscriptions insert own"
on public.nova_push_subscriptions for insert to authenticated
with check (employee_no = coalesce(((select auth.jwt()) ->> 'employee_no'), ''));

drop policy if exists "nova push subscriptions update own" on public.nova_push_subscriptions;
create policy "nova push subscriptions update own"
on public.nova_push_subscriptions for update to authenticated
using (employee_no = coalesce(((select auth.jwt()) ->> 'employee_no'), ''))
with check (employee_no = coalesce(((select auth.jwt()) ->> 'employee_no'), ''));

drop policy if exists "nova push subscriptions delete own" on public.nova_push_subscriptions;
create policy "nova push subscriptions delete own"
on public.nova_push_subscriptions for delete to authenticated
using (employee_no = coalesce(((select auth.jwt()) ->> 'employee_no'), ''));

create or replace function nova_private.nova_push_subscription_claim_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_employee_no text := coalesce(((select auth.jwt()) ->> 'employee_no'), '');
begin
  if coalesce(v_employee_no,'') = '' or new.employee_no <> v_employee_no then
    raise exception 'push subscription employee mismatch';
  end if;
  -- A shared/reused phone endpoint can belong to only the currently signed-in employee.
  delete from public.nova_push_subscriptions s
  where s.endpoint = new.endpoint
    and s.employee_no <> new.employee_no;
  new.updated_at := now();
  new.last_seen_at := now();
  return new;
end;
$function$;
revoke all on function nova_private.nova_push_subscription_claim_trigger() from public, anon, authenticated;

drop trigger if exists nova_push_subscription_claim_trg on public.nova_push_subscriptions;
create trigger nova_push_subscription_claim_trg
before insert on public.nova_push_subscriptions
for each row execute function nova_private.nova_push_subscription_claim_trigger();

create table if not exists public.nova_push_delivery_runs (
  push_run_id bigint generated by default as identity primary key,
  notification_id bigint not null references public.nova_notifications(notification_id) on delete cascade,
  employee_no text not null,
  attempted_at timestamptz not null default now(),
  completed_at timestamptz null,
  delivered integer not null default 0,
  gone integer not null default 0,
  failed integer not null default 0,
  error_summary text not null default ''
);
create index if not exists nova_push_delivery_runs_notification_idx
  on public.nova_push_delivery_runs (notification_id, attempted_at desc);
alter table public.nova_push_delivery_runs enable row level security;
revoke all on table public.nova_push_delivery_runs from public, anon, authenticated;

create or replace function public.nova_web_push_config_service()
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  v_private text;
begin
  select s.decrypted_secret into v_private
  from vault.decrypted_secrets s
  where s.name='nova_web_push_vapid_private_v2'
  limit 1;
  if coalesce(v_private,'')='' then raise exception 'VAPID private key unavailable'; end if;
  return jsonb_build_object(
    'publicKey','BKjiczDO9sG0qlh0rJDduCzQqT9tURU69oKN7mKmlyU4mnjx05x1FkUy-4Kaeqy40DReDmnQ1DR2s0ELu-SAgYM',
    'privateKey',v_private,
    'subject','https://evoetxfjmkkjptucwxsv.supabase.co'
  );
end;
$function$;
revoke all on function public.nova_web_push_config_service() from public, anon, authenticated;
grant execute on function public.nova_web_push_config_service() to service_role;

create or replace function nova_private.nova_notification_web_push_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_token text;
  v_request_id bigint;
begin
  if not exists (
    select 1 from public.nova_push_subscriptions s
    where s.employee_no=new.recipient_employee_no and s.enabled=true
  ) then
    return new;
  end if;

  select s.decrypted_secret into v_token
  from vault.decrypted_secrets s
  where s.name='nova_web_push_dispatch_token_v2'
  limit 1;
  if coalesce(v_token,'')='' then return new; end if;

  -- Push is deliberately async/best-effort: it must never block the core NOVA write path.
  begin
    select net.http_post(
      url := 'https://evoetxfjmkkjptucwxsv.supabase.co/functions/v1/nova-web-push-v2',
      body := jsonb_build_object('notificationId',new.notification_id),
      params := '{}'::jsonb,
      headers := jsonb_build_object(
        'Content-Type','application/json',
        'X-NOVA-Web-Push-Token',v_token
      ),
      timeout_milliseconds := 15000
    ) into v_request_id;
  exception when others then
    null;
  end;
  return new;
end;
$function$;
revoke all on function nova_private.nova_notification_web_push_trigger() from public, anon, authenticated;

drop trigger if exists nova_notification_web_push_trg on public.nova_notifications;
create trigger nova_notification_web_push_trg
after insert on public.nova_notifications
for each row execute function nova_private.nova_notification_web_push_trigger();